import 'package:cloud_firestore/cloud_firestore.dart';

class SemesterModel {
  final String id;
  final String code;
  final String name;
  final bool isCurrent;
  final DateTime createdAt;
  final DateTime? updatedAt;

  SemesterModel({
    required this.id,
    required this.code,
    required this.name,
    this.isCurrent = false,
    required this.createdAt,
    this.updatedAt,
  });

  // Convert to Map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'code': code,
      'name': name,
      'isCurrent': isCurrent,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
    };
  }

  // Create from Firestore document
  factory SemesterModel.fromMap(Map<String, dynamic> map, String documentId) {
    return SemesterModel(
      id: documentId,
      code: map['code'] ?? '',
      name: map['name'] ?? '',
      isCurrent: map['isCurrent'] ?? false,
      createdAt: (map['createdAt'] as Timestamp).toDate(),
      updatedAt: map['updatedAt'] != null 
          ? (map['updatedAt'] as Timestamp).toDate() 
          : null,
    );
  }

  // Create from CSV row
  factory SemesterModel.fromCsv(List<dynamic> row) {
    return SemesterModel(
      id: '', // Will be generated by Firestore
      code: row[0].toString().trim(),
      name: row[1].toString().trim(),
      isCurrent: false,
      createdAt: DateTime.now(),
    );
  }

  // Copy with method for updates
  SemesterModel copyWith({
    String? id,
    String? code,
    String? name,
    bool? isCurrent,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return SemesterModel(
      id: id ?? this.id,
      code: code ?? this.code,
      name: name ?? this.name,
      isCurrent: isCurrent ?? this.isCurrent,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}