// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDP5gUJzH5HMRJkIvNUwK1lrXlNT4Dqs',
    appId: '1:395461863551:web:196ff8704b89652d85774a',
    messagingSenderId: '395461863551',
    projectId: 'educate-classroom',
    authDomain: 'educate-classroom.firebaseapp.com',
    storageBucket: 'educate-classroom.firebasestorage.app',
    measurementId: 'G-YHKB634LZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFYtAB4awMjc63VD3IMi9VzKtZkub04k',
    appId: '1:395461863551:android:ba57c5ae933d500385774a',
    messagingSenderId: '395461863551',
    projectId: 'educate-classroom',
    storageBucket: 'educate-classroom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrYg9o_UmvV0kGyCpunRtoKqCMSezuUc',
    appId: '1:395461863551:ios:9085682d3f0357f585774a',
    messagingSenderId: '395461863551',
    projectId: 'educate-classroom',
    storageBucket: 'educate-classroom.firebasestorage.app',
    iosBundleId: 'com.example.educateClassroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrYg9o_UmvV0kGyCpunRtoKqCMSezuUc',
    appId: '1:395461863551:ios:9085682d3f0357f585774a',
    messagingSenderId: '395461863551',
    projectId: 'educate-classroom',
    storageBucket: 'educate-classroom.firebasestorage.app',
    iosBundleId: 'com.example.educateClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDP5gUJzH5HMRJkIvNUwK1lrXlNT4Dqs',
    appId: '1:395461863551:web:40441db316b3f73e85774a',
    messagingSenderId: '395461863551',
    projectId: 'educate-classroom',
    authDomain: 'educate-classroom.firebaseapp.com',
    storageBucket: 'educate-classroom.firebasestorage.app',
    measurementId: 'G-4730PHQ6V5',
  );

}